### PR TITLE
Fix #910

### LINKED ISSUE #910: Add a function to prevent autologin when the email link is clicked
**Describe the bug**
This is an issue that is also directly similar to the issue here [https://github.com/TycheSoftwares/woocommerce-abandon-cart-pro/issues/3110](https://github.com/TycheSoftwares/woocommerce-abandon-cart-pro/issues/3110) regarding how we allow users/customers to be automatically logged-in anytime they click on the checkout link in the reminder emails.

One of our users also reached out regarding this issue in the lite version and according to him, he pointed out the security flaw associated with this method below:

> Seems that Abandoned Cart Lite sends emails to customers with a cart link that actually logs them into their account; meaning that if they forward that email to anyone; that person is instantly logged in as that customer.

The likely solutions which will work for this are the same which were implemented on the pro version 2 months ago. They are:

(1) We can redirect the user/customer to the login page after clicking on the link in the abandoned cart reminder email. This will ensure that each customer signs first before completing the purchase.

(2) We go with what the client suggested by adding a function that allows the admin to enable or disable the user session on the admin backend. A login link can also be created to add items to cart, even without forcing the user to login.

**Additional context**
[https://tychesoftwares.freshdesk.com/a/tickets/55446](https://tychesoftwares.freshdesk.com/a/tickets/55446)

### PR DESCRIPTION
**Pull request by nidhitatosaniya**
Added a function to prevent autologin when the email link is clicked.

### CODE REVIEW

File: woocommerce-ac.php [hunk 1]
```diff
@@ -1956,12 +1989,20 @@ public function wcal_email_track_links( $template ) {
...
+						$my_temp = wc_load_persistent_cart( $user_login, $user );
+						do_action( 'wp_login', $user_login, $user );
+						if ( isset( $sign_in ) && is_wp_error( $sign_in ) ) {
+							echo esc_html( $sign_in->get_error_message() );
+							exit;
+						}
+					} else {
+						wp_set_auth_cookie( $user_id, false, '', 'loggedout' );
+						$my_temp = wc_load_persistent_cart( $user_login, $user );
+						set_transient( 'wcal_email_sent_id', $email_sent_id, 1800 );
```
Comment (pinalj) [inline woocommerce-ac.php:2003]: The feature seems to be incompletely coded. The transients set here are not used anywhere @nidhitatosaniya 

Please let me know if I've missed anything.

**Review by pinalj — CHANGES_REQUESTED** [review]
The feature seems to be incompletely coded. I'm unable to find the patch of code where the transients set here are being used.

**Review by pinalj — APPROVED** [review]
